# Generated by Django 2.2.2 on 2019-06-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190606_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details_retail',
            field=models.CharField(default='Kg', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='details_wholesale',
            field=models.CharField(default='Per dozen', max_length=20),
        ),
    ]
