# Generated by Django 2.2.2 on 2019-06-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190607_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='details_retail',
            new_name='retail_details',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='details_wholesale',
            new_name='wholesale_details',
        ),
    ]
